version: '3'
services:
  Visualizer:
    build: ./Visualizer
    volumes:
      - ./Visualizer:/Visualizer
    #ports:
    #  - 5000:3306
    working_dir: /Visualizer

  Detector:
    build: ./Detector
    volumes:
      - ./Detector:/Detector
    #ports:
    #  - 5000:3306
    working_dir: /Detector

  FusionFramework:
    build: ./FusionFramework
    volumes:
      - ./FusionFramework:/FusionFramework
    #ports:
    #  - 5000:3306
    working_dir: /FusionFramework
